# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - 'lib/**/*.g.dart'
    - 'lib/**/*.freezed.dart'

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    avoid_multiple_declarations_per_line: false
    prefer_relative_imports: true # https://stackoverflow.com/a/66188522/12421326
    always_use_package_imports: false
    require_trailing_commas: false
    # Rationale: in our app, the codes are for reading on mobile phones, adding
    # `this` makes it easier for readers to understand which variables class
    # members and which ones are not.
    unnecessary_this: false
    # Same as above, allow writing local variable types to improve readability
    # without IDE.
    # We sometimes have print statements just for demo purposes.
    avoid_print: false
    omit_local_variable_types: false
    use_colored_box: false
    use_decorated_box: false
    no_leading_underscores_for_local_identifiers: false
    use_string_buffers: false
    avoid_redundant_argument_values: false
    prefer_const_constructors: false
    avoid_dynamic_calls: false
    directives_ordering: false
    sort_pub_dependencies: false
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
